
const PADDING_HORIZONTALLY_XXS = 3.0;
const PADDING_HORIZONTALLY_XS = 5.0;
const PADDING_HORIZONTALLY_S = 7.0;
const PADDING_HORIZONTALLY = 10.0;
const PADDING_HORIZONTALLY_L = 15.0;
const PADDING_HORIZONTALLY_XL = 20.0;
const PADDING_HORIZONTALLY_XXL = 30.0;
const PADDING_HORIZONTALLY_XXXL = 50.0;

const PADDING_VERTICALLY_XXS = 5.0;
const PADDING_VERTICALLY_XS = 10.0;
const PADDING_VERTICALLY_S = 15.0;
const PADDING_VERTICALLY = 20.0;
const PADDING_VERTICALLY_L = 25.0;
const PADDING_VERTICALLY_XL = 30.0;
const PADDING_VERTICALLY_XXL = 40.0;


const ELEVATION_XXS = 3.0;
const ELEVATION_XS = 5.0;
const ELEVATION_S = 7.0;
const ELEVATION = 10.0;
const ELEVATION_L = 15.0;
const ELEVATION_XL = 20.0;
const ELEVATION_XXL = 25.0;

const FONT_SIZE = 16.0;
const FONT_SIZE_L = 18.0;
const FONT_SIZE_XL = 20.0;
const FONT_SIZE_XXL = 25.0;
const FONT_SIZE_XXXL = 30.0;


const SPACER = 15.0;
const SPACER_L = 20.0;
const SPACER_XL = 25.0;
const SPACER_XXL = 30.0;

const BUTTON_HEIGHT = 40.0;
const BUTTON_HEIGHT_L = 50.0;
const BUTTON_HEIGHT_XL = 60.0;

const BORDER_RADIUS = 15.0;
const BORDER_RADIUS_L = 20.0;
const BORDER_RADIUS_XL = 25.0;
const BORDER_RADIUS_XXL = 35.0;

const ICON_SIZE_XXS = 15.0;
const ICON_SIZE_XS= 20.0;
const ICON_SIZE_S = 23.0;
const ICON_SIZE = 25.0;
const ICON_SIZE_L = 40.0;
const ICON_SIZE_XL = 45.0;
const ICON_SIZE_XXL = 50.0;

const CIRCLE_BUTTON_SIZE = 30.0;

/// rarely used

const TOP_BAR_HEIGHT = 80.0;
const BOTTOM_BAR_HEIGHT = 120.0;