
const PADDING_HORIZONTALLY_XXS = 3.0;
const PADDING_HORIZONTALLY_XS = 5.0;
const PADDING_HORIZONTALLY_S = 7.0;
const PADDING_HORIZONTALLY = 10.0;
const PADDING_HORIZONTALLY_L = 15.0;
const PADDING_HORIZONTALLY_XL = 20.0;
const PADDING_HORIZONTALLY_XXL = 30.0;

const PADDING_VERTICALLY_XXS = 5.0;
const PADDING_VERTICALLY_XS = 10.0;
const PADDING_VERTICALLY_S = 15.0;
const PADDING_VERTICALLY = 20.0;
const PADDING_VERTICALLY_L = 25.0;
const PADDING_VERTICALLY_XL = 30.0;
const PADDING_VERTICALLY_XXL = 40.0;

const SPACER = 15.0;
const SPACER_L = 20.0;
const SPACER_XL = 25.0;
const SPACER_XXL = 30.0;
